### ISSUE TITLE
Add a code-test to ensure that filter lists perfectly match nam files

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/glyphsets#1]
Originally posted at https://github.com/googlefonts/gftools/issues/361 on April 14, 2021.

While talking to @vv-monsalve today we noticed that there's a risk that the filter lists may at some point diverge from the .nam file by mistake. It would be good to have automated tests to ensure that never happens.

**Comment by simoncozens** [comment]
Nam files are about codepoints and filter lists are about glyphs, so I would be surprised if they did *not* diverge.

**Comment by felipesanches** [comment]
thanks
