### ISSUE TITLE
Should the Google Fonts Latin African contain "Latin Small Letter Ezh Reversed"?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/glyphsets#124]
(Similar to #119 opened by @EbenSorkin)

A user wrote in to fonts@google.com with the following

> We are writing to you today to request that you support us in including the Kelme characters in your fonts. The Kelme writing system is a Unicode Latin-based writing system for the Lebanese dialect and other Semitic dialects. It is used by thousands of Lebanese people in the diaspora to communicate and write in Lebanese efficiently.
> 
> The main missing characters in mainstream fonts are:
> 1. Ƹ (ƹain majuscule): U+01B8
> 2. ƹ (ƹain minuscule): U+01BC
> 3. Ə (hamze majuscule): U+0259
> 4. ɂ (hamze miniscule): U+025B
>
> The Lebanese dialect is often considered a dialect of Arabic, but it has its own unique phonetics and nuances. Writing Lebanese in Arabic script is not inclusive but remains important for mutual intelligibility for Arabic readers. That being said, we have identified a need for more phonetic nuances and the ability to easily teach a writing system to the Lebanese community in the diaspora that may not learn Arabic script. The Kelme writing system is designed to be an accurate and efficient way to write the Lebanese dialect.
> 
> We would also appreciate your help in identifying the current fonts that are inclusive of all of our characters if possible. Here is the list of characters: AÁBCČDḌEÉFGĠHḤIÍJKḲLMƸOÓPƏQRSṢTṬUÚÜVWXYZŻ / aábcčdḍeéfgġhḥíjkḳlmnƹópɂqrsṣtṭuúüvwxyzż
> 
> Thank you for your time and consideration.
>
> [kelme-lb.com](https://www.kelme-lb.com)

`Ƹ` is in GF Latin African (https://github.com/search?type=code&q=repo%3Agooglefonts%2Fglyphsets+01B8)

`ƹ` is not yet in any set (https://github.com/search?type=code&q=repo%3Agooglefonts%2Fglyphsets+01BC) 

`Ə` is in GF Latin Beyond (https://github.com/search?type=code&q=repo%3Agooglefonts%2Fglyphsets+0259)

`ɂ` is in GF Latin Beyond (https://github.com/search?type=code&q=repo%3Agooglefonts%2Fglyphsets+025B)

So, I propose to add `ƹ` to the GF Latin African set.

**Comment by davelab6** [comment]
Doh, after double checking, `ƹ` is actually U+[01B9](https://github.com/search?type=code&q=repo%3Agooglefonts%2Fglyphsets+01B9)) which **is already in the African set**, not U+01BC which is another character and a typo by the person who reached out. So, nothing to do here :)

**Comment by moyogo** [comment]
@davelab6 What is your definition of GF Latin African? Lebanese Arabic isn’t African. Considering #123 which would remove a lot of glyphs not used in African languages, should the set be redefined and renamed?
