### ISSUE TITLE
Add design right mark to latin plus

### ISSUE THREAD

**Issue by davelab6** [googlefonts/glyphsets#217]
from @tphinney 

> Seems like we have to keep an eye on EU design regulations. They are in the process of approving a new symbol for design protection, which could both be applied to fonts, and give us another character to support in fonts.
> 
> Capital D in a circle is already encoded at U+24B9, but not present in most fonts.
> 
> https://www.linkedin.com/pulse/here-comes-new-symbol-design-font-protection-production-type-44yie/
>

**Comment by yanone** [comment]
Solved
