### ISSUE TITLE
GF Latin Africa set

### ISSUE THREAD

**Issue by davelab6** [googlefonts/glyphsets#23]
https://twitter.com/r12a/status/1157943086695223296?s=19

Add a Latin set for these

**Comment by moyogo** [comment]
This set mixes orthographies and phonetic transcriptions: ð ɟ λ ɴ ⱴ θ are not used in African Latin orthographies but are used IPA or phonetic transcriptions. The λ and θ are used in American Latin orthographies.

It also has a couple of characters that shouldn’t be there:
The letter ǌ ꝗ are mistakes, ǌ is a digraph that shoudl be two characters n and j, ꝗ is a Latin abbreviation.

**Comment by moyogo** [comment]
Technically ð and q̱ (mistaken for ꝗ) are in the UNESCO 1978 African Reference Alphabet but haven’t been used as far as I know. The Mann and Dalby 1982 African Reference Alphabet has the other ɟ λ θ and a variation of ɴ but they have the same issue.
