### ISSUE TITLE
nam file format niggle

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/glyphsets#232]
Currently the glyphsets nam files are produced in the following format:

```
0xDEADBEEF COMBINING RUMP STEAK
```

which is fine and matches what's going on in the nam-files repo. However, if we made them look like this instead:

```
0xDEADBEEF # COMBINING RUMP STEAK
```

then they can be directly used as input to `hbsubset`/`fonttools subset`, which would be very handy.

**Comment by yanone** [comment]
Implemented
