### ISSUE TITLE
GF Latin Plus includes ₧ (peseta), a mostly unused symbol for an historical currency. Should it?

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/glyphsets#38]
The [Spanish peseta](https://en.wikipedia.org/wiki/Spanish_peseta) has been out of use for at least 20 years (since the introduction of the Euro). Additionally, the `₧` (P plus bar) symbol potentially doesn’t seem to be used as much as the "Pts" version of the glyph.

Should it really be in the GF Latin Plus glyph set? If so, is there a reason?

Related: https://github.com/googlefonts/glyphsets/issues/37

Thanks!

**Comment by davelab6** [comment]
As @RosaWagner said in #37, 

> This is planned in https://github.com/googlefonts/glyphsets/pull/36/files#diff-deb67e1abe331b32c4d92df0424d086fa76c2861e0b1a7337ba935e70eaaa8d7
>
> <img width="330" alt="Capture d’écran 2022-01-07 à 17 29 56" src="https://user-images.githubusercontent.com/12222436/148574934-a25794d1-faa6-4ff5-a3d2-f81bcfe4e1ab.png">
