### ISSUE TITLE
Add all nam files

### ISSUE THREAD

**Issue by davelab6** [googlefonts/glyphsets#8]
There is a list of subsets here,

https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/subsets.py

But the set of 'nam' subset files does not have files for every item in that list

https://github.com/googlefonts/glyphsets/tree/main/Lib/glyphsets/encodings 

We should fix this.

**Comment by simoncozens** [comment]
This is stale, but I think it's about the designer glyphset / engineering subset distinction.
