### ISSUE TITLE
UCAS Extended A Block

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/glyphsets#86]
This was added in Unicode 14.0, and is supported by Noto Sans UCAS, but we subset it out because we don't have a glyphset definition for it. Should it go into canadian-aboriginal_unique-glyphs or its own thing?

**Comment by marekjez86** [comment]
My advice would be to add it to canadian-aboriginal_unique-glyphs, but how do we treat other extended blocks (e.g, Arabic)?
How about Georgian upper case U+1C90..U+1CBF ?

**Comment by simoncozens** [comment]
Georgian uppercase is missing as well. (Really, there should be glyphset coverage for all the Unicode codepoints we support. I should make another test!)

As for which file, there's no system. Arabic has one file, as does Devanagari; but Cyrillic / Cyrillic Ext are separate, as are Tamil/Tamil Supplement. I would personally prefer to put separate Unicode blocks into separate files, as it makes them easier and less surprising to audit. But I still feel like I am missing something about the whole point of these files anyway...

**Comment by LornaSIL** [comment]
> Arabic has one file

But Arabic only has a very minor subset of everything in the Arabic blocks. I'd love for there to be a better system so fonts that support non-majority languages aren't subsetting out the support that they have for non-majority languages.

**Comment by simoncozens** [comment]
> I'd love for there to be a better system so fonts that support non-majority languages aren't subsetting out the support that they have for non-majority languages.

I really feel like I'm missing something about how (or more to the point, *why*) the subsetter works, but so often the problem I have with Noto (and the problem you have with Arabic) goes something like "The subsetter is removing codepoints from our fonts. But we put those codepoints in our fonts on purpose, so that people can use them."

The way to work around this is to add all Unicode codepoints we need to the glyphset definitions. But we (potentially) need all of them. Maybe eventually we'll add *all* the Unicode codepoints, so that the subsetter is a no-op, and then the problems will be fixed.
