### ISSUE TITLE
IPA Extensions nam files

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/glyphsets#88]
No nam files cover the IPA extensions block, even though a substantial number of these codepoints are used in African Latin and are already scoped for designers as part of GF Latin Plus. (This is the cause of notofonts/latin-greek-cyrillic#174)

(This is not exhaustive. There are almost certainly other entire Unicode blocks where we have fonts which cover them, but we subset away so they can't be used on the platform. It's the same problem as the UCAS issue #86 and the extended Arabic issue #68. If our nam files do not cover all of Unicode - which they don't - then the inevitable result will be that there are characters which people want to use, but they can't.)

**Comment by NeilSureshPatel** [comment]
Sorry, a bit slow to respond to this thread. I am traveling at the moment. We are currently looking at the issue of Pan-African Latin support across the entire Google Fonts library, which includes any Noto fonts that are included in the [Google Fonts Repo](https://github.com/google/fonts).  

There is meeting to look at the results of the shaperglot analysis @simoncozens and I worked on on Feb 7th. I believe the entire Google Fonts team is invited. The broader question on how to best support language preferences needs to be resolved. Currently, I am recommending that un-encoded glyph variants like that needed for the Eng in African languages be supported using the locl feature providing that a corresponding OT language tag exists. As mentioned in the issue mentioned above, the biggest drawback is that African language tag coverage is sparse compared to European language tag coverage. This will require having new tags added to the OT spec. An alternative approach is to make some of the African glyph variants the default and using the locl feature to access the European forms. This is a discussion that needs to take place. 

Regarding the glyph sets, I have compiled a Pan-African Latin glyphset. At this point I don't know if there is a need to combine some of the higher priority African language glyphs into other glyphsets or not. At this point, we have a handle on everything we need for African language support, we just need to sort out what the best implementation is based on the different use cases for Noto/Google Fonts.

**Comment by andjc** [comment]
@NeilSureshPatel locl is a suboptimal approach, essentially it means you are cherry-picking some languages to support and excluding others from being supported. For instance, using local to handle the African vs Sami situation means that a number of Indigenous languages here will get excluded, nor does it help in digitising older documents that had other choices.  locl is one tool, but other approaches like CV features should also be in the mix, good language coverage will only happen if a flexible approach is taken.

**Comment by NeilSureshPatel** [comment]
@andjc I think it would be good to map out all the use cases for the Noto fonts against the ways different features can fail for those cases. Do you know of this is already documented somewhere? I have very little understanding of all the ways Noto fonts are subset or how they are bundled and distributed. I agree locl is problematic. However, if for example an African lang subset is a different than a European subset then some of the conflicts are resolved. I can also see having multiple approaches like some combo of CV and locl, etc to make things more robust.

**Comment by andjc** [comment]
> Do you know of this is already documented somewhere?

In general, no, not for Noto, there are bits and pieces scattered through open and closed issues. But other than SIL with their fonts, few have bothered to even partially map requirements, and SIL's approach hasn't been locl based for Latin glyph variants.

So a lot of time and resourcing would be needed to map it properly.

> However, if for example an African lang subset is a different than a European subset then some of the conflicts are resolved.

To do it properly you need to tick off African, Northern European, Asian, Australian and North American usage, and I am not sure whether that is practical using locl.

**Comment by andjc** [comment]
@NeilSureshPatel I started some work on a CSS framework that would kick in OpenType features, either through language pseudo-class or via classes targeting OpenType features.

**Comment by simoncozens** [comment]
My general approach to these things is "we do the right thing, and then we fix the tools so that others get the benefit". The "right thing" when it comes to language selection in fonts is the `locl` feature. If this means we need new language tags added to OpenType, OK, let's get them added (it's not controversial and there's an OFF revision in April, so no big deal); browsers are pretty cool with language tagging, but if other software needs better `locl` support, OK, let's agitate for that to happen. 

Yes, I'm also a pragmatist and we should also use character variants in the interim so people can use InDesign too, but throwing our hands up in the air because the infrastructure is bad does not help the infrastructure to get better.

Anyway, the issue *here* is IPA support in the Google Fonts subsetter, and I think I now have a handle on how to fix that.

**Comment by LornaSIL** [comment]
Years ago I came up with a list of characters I thought should be in a "Phonetics" set (not just IPA since Americanists want other characters too). This is what I came up with:
https://scriptsource.org/entry/y7gu4ubr5h

The link to all the Latin sets I came up with are available here:
https://scriptsource.org/entry/t38atsqf2c

**Comment by simoncozens** [comment]
I think it's simpler than that. An IPA nam file should cover the whole IPA block, plus any combining characters that will need to combine with them. The Latin glyphs will be pulled from the Latin nam.
